### ISSUE TITLE
Loops found depends on order in adjacency list.

### ISSUE THREAD

**Issue by polishdude20** [antoinerg/elementary-circuits-directed-graph#11]
I have an adjacency list like so:
const adj = [
    [1],
    [0, 6, 3, 2],
    [1, 4, 6],
    [1, 4, 6],
    [2, 3, 5, 6],
    [4],
    [1, 2, 3, 4]
];

This one above detects all the loops in the graph.

If I change the 1st index values to be [0,2,3,6], the loop output is different and it misses a loop.
Is this supposed to happen? Changing the order of the number in the adjacency graph shouldn't change the output.

**Comment by polishdude20** [comment]
I just realized that this tool is doing what it should be doing but I am using this to detect all loops in an undirected graph.  Is there a modification that can be easily made to detect all loops in an undirected graph?

**Comment by antoinerg** [comment]
I'm not sure what a loop is if there is no directions in the graph.

> Is there a modification that can be easily made to detect all loops in an undirected graph?

I'm not sure. But this package is meant to do only one task: finding elementary circuits in a directed graph. I will therefore close this issue.

Thank you for your interest @polishdude20
